version: '3.8'

services:
  db:
    image: postgres
    container_name: newssite_db
    environment:
      - POSTGRES_DB=NewsSite
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
  web:
    build: .
    container_name: newssite_web
    command: ["./wait-for-it.sh", "db:5432", "--", "python", "manage.py", "runserver", "0.0.0.0:8000"]
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db

